@startuml

title Class diagram: ctd_processing

class _old_ctd_sbe9_processing.CtdProcessing #1559F3 {
	+alignctd
	+batch_file
	+binavg
	+bottlesum
	+celltm
	+cnty
	+cnv_column_info
	+ctdNo
	+ctd_data
	+ctdconfig, @ca
	+ctdmodule_file
	+ctdnumber, @ca
	+data_directory
	+datacnv
	+deep_surfacesoak, @ca
	+derive
	+filter
	+if, @ca
	+loopedit
	+manuell_surfacesoak, @ca
	+new_fname
	+number_of_bottles
	+plot1
	+plot2
	+plot3
	+plot4
	+plot_directory
	+raw_files_directory
	+serie
	+ship
	+split
	+stationname
	+working_directory
	+year
==
	+check_bl()
	+copy_files_to_server()
	+create_batch_file()
	+get_file()
	+get_string_for_data_file()
	+get_string_for_shark_file()
	+load_options()
	+modify_cnv_file()
	+run_seabird()
}

class bl_file.BlFile #C2530C {
	+file_path
	-_number_of_bottles
	number_of_bottles, @p
==
	-_save_number_of_bottles()
}

class bokeh_server.CTDBokehQC #9A9BC7 {
	-_bokeh_server
	-_run_bokeh_server_bat_file
	-_run_bokeh_server_file
	-_run_bokeh_server_template_file
==
	+set_data_directory()
	+start_bokeh_server()
	+stop_bokeh_server()
}

class cnv_column_info.CnvInfoFile #7C1673 {
	+file_path
	+file_stem
	+sensor_info
==
	+get_info()
	-__repr__()
	-_load_file()
}

class cnv_column_info.CnvInfoFiles #7C1673 {
	+directory
	-_files
	files, @p
==
	+get_info()
	-__repr__()
	-_load_files()
}

class cnv_column_info.CnvSensorInfo #7C1673 {
	-_file_path
	file, @p
	name, @p
==
	-__repr__()
}

class cnv_file.CNVfile #334928 {
	+cnv_info_object
	+col_dens
	+col_dens2
	+col_depth
	+col_pres
	+col_sv
	+data
	+date_format_in_file
	+file_path
	+g
	+header
	+instrument_number
	+linebreak
	+missing_value
	+missing_value_str
	+nr_data_lines
	+parameters
	+use_cnv_info_format
	-_ctd_files
	-_lat
	-_lon
	-_station
	-_time
	lat, @p
	lon, @p
	station, @p
	time, @p
==
	+modify()
	+save_file()
	-_change_parameter_name()
	-_check_index()
	-_get_calculated_true_depth()
	-_get_data_rows()
	-_get_density_data()
	-_get_depth_data()
	-_get_mean_sound_velocity()
	-_get_parameter_name_matching_string()
	-_get_pressure_data()
	-_get_sound_velocity_data()
	-_load_info()
	-_modify_depth()
	-_modify_fluorescence()
	-_modify_header_information()
	-_modify_irradiance()
	-_modify_span()
	-_save_columns()
	-_set_active_parameters()
}

class cnv_file.CNVfileInfo #334928 {
	+date_format_in_file
	-_lat
	-_lon
	-_path
	-_station
	-_time
	lat, @p
	lon, @p
	station, @p
	time, @p
==
	-_get_info_from_file()
}

class cnv_file.CNVfileXML #0A1B3D {
	+path
	+tree
	+xmlstring
	serial_number, @p
==
	+get_datetime_object(), @sm
	+get_sensor_info()
	-_get_comment_for_channel()
}

class cnv_header.CNVheader #CC676D {
	+linebreak
	+rows
==
	+add_row()
	+append_to_row()
	+get_row_index_for_matching_string()
	+insert_row_after()
	+replace_row()
	+replace_string_at_index()
}

class cnv_parameter.CNVparameter #E05D5B {
	+active
	+cnv_info_object
	+info
	+name
	+sample_value
	+use_cnv_info_format
	-_data
	-_nr_decimals
	-_tot_value_length
	-_value_format
	data, @p
	format, @p
==
	+add_data()
	+change_name()
	+get_value_as_string_for_index()
	+set_active()
	+set_value_length()
	-__repr__()
	-_set_nr_decimals()
}

class data_delivery.DeliveryMetadataFile #FD8F82 {
	+template_path
	+wb
	-_metadata
	-_metadata_columns
	-_metadata_header_row
	-_metadata_sheet_name
	-_sensorinfo
	-_sensorinfo_columns
	-_sensorinfo_header_row
	-_sensorinfo_sheet_name
==
	+add_delivery_note_from_file()
	+add_metadata_from_file()
	+add_sensorinfo_from_file()
	+old_save_file()
	+old_write_metadata()
	+old_write_sensorinfo()
	+save_file()
	-_copy_template()
	-_get_header_in_worksheet()
	-_load_headers()
	-_write_df_to_xlsx()
	-_write_metadata()
	-_write_sensorinfo()
}

class delivery_note.DeliveryNote #0AE46A {
	-_comment
	-_contact
	-_data
	-_description
	-_directory
	-_paths
	-_save_path
	-_stem
==
	+write_to_file()
	-__str__()
	-_save_info()
}

class derive.DerivePSAfile #D96DC9 {
	
==
	+set_tau_correction()
	+turn_tau_correction_off()
	+turn_tau_correction_on()
}

class exceptions.CTDException #CD29E7 {
	
==
	
}

class exceptions.FileExists #CD29E7 {
	
==
	
}

class exceptions.InvalidCountryCode #CD29E7 {
	
==
	
}

class exceptions.InvalidDateFormat #CD29E7 {
	
==
	
}

class exceptions.InvalidFileNameFormat #CD29E7 {
	
==
	
}

class exceptions.InvalidInstrumentName #CD29E7 {
	
==
	
}

class exceptions.InvalidInstrumentSerialNumber #CD29E7 {
	
==
	
}

class exceptions.InvalidParameterIndex #CD29E7 {
	
==
	
}

class exceptions.InvalidSerialNumber #CD29E7 {
	
==
	
}

class exceptions.InvalidSurfacesoak #CD29E7 {
	
==
	
}

class exceptions.InvalidTimeFormat #CD29E7 {
	
==
	
}

class exceptions.MissingAttribute #CD29E7 {
	
==
	
}

class exceptions.PathError #CD29E7 {
	
==
	
}

class exceptions.UnrecognizedFileName #CD29E7 {
	
==
	
}

class file_handler.File #A68ACF {
	+path
	name, @p
	suffix, @p
==
	-__call__()
	-__eq__()
	-__str__()
}

class file_handler.SBEFileHandler #A68ACF {
	+local_files
	+paths
	+server_files
==
	+copy_files_to_server()
	+get_local_file_path()
	+not_on_server()
	+not_updated_on_server()
	+select_file()
	-_load_files()
	-_load_local_files()
	-_load_server_files()
	-_not_on_server()
	-_not_updated_on_server()
}

class file_pattern_nodc.NODCSBECTDFiles #4AF337 {
	+name, @ca
	+pattern, @ca
	+pattern_example, @ca
	config_file_suffix, @p
	instrument_number, @p
	serno, @p
	shipcode, @p
==
	-_get_proper_file_stem()
}

class file_pattern_old_processing_script.OldSBECTDFiles #E05B83 {
	+name, @ca
	+pattern, @ca
	+pattern_example, @ca
	config_file_suffix, @p
	instrument_number, @p
	serno, @p
	shipcode, @p
==
	-_get_proper_file_stem()
}

class former_cnv.CNVfile #355B3F {
	+cnv_info_object
	+col_dens
	+col_dens2
	+col_depth
	+col_pres
	+col_sv
	+ctd_processing_object
	+ctry
	+data
	+file_path
	+g
	+header
	+linebreak
	+missing_value
	+missing_value_str
	+nr_data_lines
	+parameters
	+serie
	+ship
	+use_cnv_info_format
	+year
==
	+modify()
	+save_file()
	-_change_parameter_name()
	-_check_index()
	-_get_calculated_true_depth()
	-_get_data_rows()
	-_get_density_data()
	-_get_depth_data()
	-_get_mean_sound_velocity()
	-_get_parameter_name_matching_string()
	-_get_pressure_data()
	-_get_sound_velocity_data()
	-_load_ctd_processing_object_info()
	-_load_info()
	-_modify_depth()
	-_modify_fluorescence()
	-_modify_header_information()
	-_modify_irradiance()
	-_modify_span()
	-_save_columns()
	-_set_active_parameters()
}

class former_cnv.CNVheader #355B3F {
	+linebreak
	+rows
==
	+add_row()
	+append_to_row()
	+get_row_index_for_matching_string()
	+insert_row_after()
	+replace_row()
	+replace_string_at_index()
}

class former_cnv.CNVparameter #355B3F {
	+active
	+cnv_info_object
	+info
	+name
	+sample_value
	+use_cnv_info_format
	-_data
	-_nr_decimals
	-_tot_value_length
	-_value_format
	data, @p
	format, @p
==
	+add_data()
	+change_name()
	+get_value_as_string_for_index()
	+set_active()
	+set_value_length()
	-__repr__()
	-_set_nr_decimals()
}

class former_processing.BatchFile #2D7AB4 {
	+batch_file_path
	+parent
	+setup_file_path
	+working_dir
==
	+create_file()
	+run_file()
}

class former_processing.CtdProcessing #2D7AB4 {
	+batch_file_object
	+cnv_column_info_directory
	+cnv_info_files
	+cnv_info_object
	+ctd_config_suffix
	+ctd_number
	+ctry
	+logger
	+logging_format
	+logging_level
	+modify_cnv_file_object
	+name
	+new_file_stem
	+number_of_bottles
	+overwrite
	+paths
	+seabird_files
	+serial_number
	+setup_file_object
	+ship
	+ship_id
	+ship_short_name
	+station_name
	+use_cnv_info_format
	+year
	-_ctd_number
	-_surfacesoak
	ctd_number, @p
	ctd_number_options, @p
	options, @p
	root_directory, @p
	surfacesoak, @p
	surfacesoak_options, @p
==
	+copy_files_to_server()
	+create_setup_and_batch_files()
	+load_seabird_files()
	+modify_cnv_file()
	+move_raw_files()
	+remove_files()
	+run_process()
	+run_seabird()
	+save_modified_ctd_file()
	-_copy_seabird_files()
	-_copy_setup_files()
	-_load_cnv_info_object()
	-_save_info_from_seabird_files()
	-_setup_logger()
}

class former_processing.Paths #2D7AB4 {
	+ctdmodule_file
	+directories
	+files
	+root_directory
	-_file
	root_directory, @p
==
	+get_directory()
	+get_file_path()
	-__repr__()
}

class former_processing.SetupFile #2D7AB4 {
	+ctd_config_suffix
	+ctd_number
	+lines
	+new_file_stem
	+number_of_bottles
	+parent
	+paths
	+plot_directory
	+setup_directory
	+setup_file_path
	+ship_id
	+ship_id_str
	+station_name
	+surfacesoak_options
	+working_directory
	+year
	-_parent
	-_surfacesoak
	parent, @p
	surfacesoak, @p
==
	+create_file()
	+get_all_lines()
	-_add_station_name_to_plots()
	-_create_lines()
	-_get_bottle_sum_line()
	-_save_variables()
	-_set_paths()
	-_set_ship_id_str()
	-_write_lines()
}

class former_seabird.BlFile #253104 {
	+file_suffix
	+number_of_bottles
==
	-_save_number_of_bottles()
}

class former_seabird.BtlFile #253104 {
	+file_suffix
==
	
}

class former_seabird.ConFile #253104 {
	+file_suffix
==
	
}

class former_seabird.HdrFile #253104 {
	+ctd
	+date
	+date_format_in_file
	+datum
	+file_suffix
	+new_file_stem
	+station_name
	+tid
==
	+validate_new_file_stem()
	-_check_country_code()
	-_check_date_format()
	-_check_instrument_name()
	-_check_instrument_serial_number()
	-_check_serial_number()
	-_check_ship_code()
	-_check_time_format()
	-_get_info_from_file()
	-_save_new_file_stem()
}

class former_seabird.HexFile #253104 {
	+file_suffix
==
	
}

class former_seabird.RosFile #253104 {
	+file_suffix
==
	
}

class former_seabird.SeabirdFiles #253104 {
	+ctd
	+ctry
	+date
	+datum
	+directory
	+file_classes, @ca
	+file_stem
	+files
	+new_file_stem
	+number_of_bottles
	+serial_number
	+ship
	+ship_id
	+ship_short_name
	+station_name
	+tid
==
	+move_files()
	+rename_files()
	-__repr__()
	-_load_files()
	-_load_info()
}

class former_seabird.SeabirdRawFileBase #253104 {
	+ctry
	+directory
	+file_name
	+file_path
	+file_stem
	+file_suffix
	+serial_number
	+ship
	+ship_id
	+ship_short_name
==
	+move_file()
	+rename()
	-__repr__()
	-_check_validity()
	-_load_ship()
	-_load_ship_info()
	-_save_file_path_info()
}

class former_seabird.XmlconFile #253104 {
	+file_suffix
==
	
}

class former_ship.Aranda #5C4520 {
	+name, @ca
	+ship_id, @ca
	+short_name, @ca
==
	
}

class former_ship.Aura #5C4520 {
	+name, @ca
	+ship_id, @ca
	+short_name, @ca
==
	
}

class former_ship.Dana #5C4520 {
	+name, @ca
	+ship_id, @ca
	+short_name, @ca
	serial_number, @p
==
	
}

class former_ship.FinnishShip #5C4520 {
	serial_number, @p
==
	
}

class former_ship.Meri #5C4520 {
	+name, @ca
	+ship_id, @ca
	+short_name, @ca
==
	
}

class former_ship.SBE09 #5C4520 {
	+name, @ca
	+ship_id
	+ship_id, @ca
	+short_name, @ca
	serial_number, @p
==
	-_load_info()
}

class former_ship.Ship #5C4520 {
	+fstem
	+name, @ca
	+ship_id, @ca
	+short_name, @ca
==
	-__repr__()
}

class former_ship.Svea #5C4520 {
	+name, @ca
	+ship_id, @ca
	+short_name, @ca
	serial_number, @p
==
	
}

class hdr_file.HdrFile #1D0326 {
	+date_format_in_file
	+file_path
	-_cruise_number
	-_station
	-_time
	cruise_number, @p
	station, @p
	time, @p
==
	-_get_info_from_file()
}

class instrument_file.InstrumentFile #5A0485 {
	-_info
	-_path
	-_sheets
	-_wb
==
	+get_info_for_parameter_and_sensor_id()
	-__str__()
	-_add_cnv_code_to_pars()
	-_save_info()
}

class loopedit.LoopeditPSAfile #F070C5 {
	depth, @p
==
	
}

class metadata.MetadataFile #EF4D3C {
	-_data
	-_directory
	-_paths
	-_save_path
	-_stem
==
	+write_to_file()
	-__str__()
	-_save_info()
}

class metadata.MetadataRow #EF4D3C {
	-_metadata
	-_metadata_columns
	-_path
==
	+get_info()
	+get_metadata_row_from_cnv_file()
	-_save_metadata()
}

class modify.ModifyCTDfiles #D8427A {
	
==
	-_modify_and_save_cnv_file()
}

class param_reported.ParamReported #DACD0E {
	+cnv_file_path
	+cnv_reported_names
	+instrument_file
==
	+get_reported_name()
	-_parameter_is_sensor_1(), @sm
	-_parameter_is_sensor_2(), @sm
	-_reported_name_is_sensor_1(), @sm
	-_reported_name_is_sensor_2(), @sm
	-_reported_name_matches_cnv_code(), @sm
}

class parent_abc_class.CTDFiles #05FDDF {
	-__proper_pattern, @ca
	-_file_name_info
	-_file_name_info, @ca
	-_files
	-_files, @ca
	-_original_file_path
	-_original_file_path, @ca
	-_plot_files, @ca
	all_files, @p
	parent, @p
	plot_files, @p
	proper_stem, @p
	stem, @p
	tractmethod, @p
==
	+add_processed_file_paths()
	+file_path()
	+has_file()
	+instrument_number()
	+is_valid()
	+lat()
	+lon()
	+modify_and_save_cnv_file()
	+name()
	+pattern()
	+pattern_example()
	+raw_files_extensions()
	+rename_files()
	+serno()
	+set_file_path()
	+shipcode()
	+station()
	+time()
	+year()
	-__call__()
	-__repr__()
	-__str__()
	-_check_file_stem()
	-_get_proper_file_stem()
	-_modify_and_save_cnv_file()
	-_rename_file()
	-_save_file_paths()
}

class paths.SBEPaths #BF3857 {
	-_paths
	-_sub_dir_list_local
	-_sub_dir_list_server
	-_year
	local_sub_directories, @p
	server_sub_directories, @p
	year, @p
==
	+create_local_paths()
	+create_server_paths()
	+get_local_directory()
	+get_path()
	+get_server_directory()
	+set_config_root_directory()
	+set_local_root_directory()
	+set_server_root_directory()
	+set_year()
	-__call__()
	-_get_server_directory_for_year()
	-_local_key()
	-_server_key()
}

class psa_file.PSAfile #C16AE5 {
	+file_path
	+tree
==
	+list_all()
	+save()
	-_get_element_from_tag_list()
	-_get_from_tag_list()
	-_get_value_list()
	-_has_condition()
	-_set_from_tag_list()
}

class psa_file_with_plot.PSAfileWithPlot #2DB4CD {
	+blueprint_display_parameter_tags
	+display_depth_tags
	+display_nr_bins_tags
	+display_nr_minor_bins_tags
	+display_parameter_tags
	+parameter_max_tag
	+parameter_min_tag
	display_depth, @p
	nr_bins, @p
==
	+get_displayed_parameters()
	+get_parameter_range()
	+set_parameter_range()
	-_get_tag_list_for_parameter()
}

class psa_plot_file.PlotPSAfile #16CA71 {
	+blueprint_display_parameter_tags
	+display_depth_tags
	+display_parameter_tags
	+parameter_max_tag
	+parameter_min_tag
	+title_tags
	title, @p
==
	
}

class sbe_batch_file.SBEBatchFile #144E2C {
	-_paths
	-_processing_paths
==
	+create_file()
	+run_file()
}

class sbe_parent_class.SBECTDFiles #E28F13 {
	+raw_files_extensions, @ca
	-_plot_files
	file_path, @p
	lat, @p
	lon, @p
	number_of_bottles, @p
	station, @p
	time, @p
	tractmethod, @p
	year, @p
==
	+add_processed_file_paths()
	+config_file_suffix()
	-_add_local_cnv_file_path()
	-_check_hdr_file()
}

class sbe_processing.SBEProcessing #65FA57 {
	-_batch_file
	-_confirmed
	-_ctd_files
	-_file_path
	-_overwrite
	-_paths
	-_processing_paths
	-_setup_file
	platform, @p
	year, @p
==
	+confirm_file()
	+create_sensorinfo_file()
	+get_file_names_in_server_directory()
	+get_platform_options()
	+get_surfacesoak_options()
	+run_process()
	+select_file()
	+set_platform()
	+set_surfacesoak()
	+set_tau_state()
	-_copy_all_files_with_same_file_stem_to_working_dir()
	-_copy_cnv_files_to_local()
	-_copy_file()
	-_copy_plot_files_to_local()
	-_copy_processed_files_to_local()
	-_copy_raw_files_to_local()
	-_get_derive_psa_obj()
}

class sbe_processing_paths.SBEProcessingPaths #459B99 {
	+sbe_paths
	-_loopedit_paths
	-_new_file_stem
	-_paths
	-_platform
	-_platform_paths
	-_psa_names
	loopedit_paths, @p
	platform, @p
	platforms, @p
==
	+set_config_suffix()
	+set_loopedit()
	+set_raw_file_path()
	+update_paths()
	-__call__()
	-__repr__()
	-__str__()
	-_build_cnv_file_paths_with_new_file_stem()
	-_build_loopedit_file_paths()
	-_build_psa_file_paths()
	-_build_raw_file_paths_with_new_file_stem()
	-_get_all_psa_paths()
	-_get_paths_in_directory(), @sm
	-_save_platform_paths()
}

class sbe_setup_file.SBESetupFile #BAF9AF {
	-_ctd_files
	-_paths
	-_proc_paths
==
	+create_file()
	-_add_station_name_to_plots()
	-_get_bottle_sum_line()
	-_get_lines()
	-_write_lines()
}

class seasave.SeasavePSAfile #44ACCF {
	+add_samp_tags
	+blueprint_display_parameter_tags
	+cruise_tags
	+data_file_tags
	+display_depth_tags
	+display_nr_bins_tags
	+display_nr_minor_bins_tags
	+display_parameter_tags
	+event_id_tags
	+lat_tags
	+lon_tags
	+metadata_admin_tags
	+metadata_conditions_tags
	+operator_tags
	+parameter_max_tag
	+parameter_min_tag
	+parent_event_id_tags
	+ship_tags
	+station_tags
	+xmlcon_name_tags
	add_samp, @p
	cruise, @p
	data_path, @p
	event_id, @p
	metadata_admin, @p
	metadata_conditions, @p
	operator, @p
	parent_event_id, @p
	position, @p
	ship, @p
	station, @p
	xmlcon_path, @p
==
	
}

class sensor_info_file.SensorInfoFile #105B45 {
	+cnv_info
	+instrument_file
	-_data
	-_save_path
	-_stem
==
	+create_file_from_cnv_file()
	-__str__()
	-_add_header_information_to_cnv_info()
	-_save_file()
	-_save_xml_data_from_cnv()
}

class sensor_info_file.SensorInfoFiles #105B45 {
	-_directory
	-_paths
	-_sensor_info_items
==
	+old_write_summary_to_file()
	+write_summary_to_file()
	-_save_info()
}

class sensor_info_item.SensorInfoItem #8FF4A7 {
	-_all_columns
	-_calibration_dates
	-_columns
	-_data
	-_key
	-_valid_from
	-_valid_to
	valid_from, @p
	valid_to, @p
==
	+add_data()
	+get_info()
	+get_key(), @sm
	-_add_additional_data()
	-_add_calibration_date()
	-_add_first_data()
	-_add_info()
	-_check_columns()
	-_get_time_object(), @sm
	-_get_time_string(), @sm
	-_set_valid_from()
	-_set_valid_to()
}

class standard_format.CreateStandardFormat #0BED99 {
	+delivery_metadata_file_path
	+paths
	-_cnv_files
	-_deliverynote_file_path
	-_export_directory
	-_metadata_file_path
	-_metadata_path
	-_output_dir
	-_overwrite
	-_sensorinfo_file_path
==
	+create_files_from_cnv()
	+old_create_delivery_metadata_file()
	-_copy_standard_format_files_to_local()
	-_create_deliverynote_file()
	-_create_metadata_file()
	-_create_sensorinfo_file()
	-_create_standard_format_files()
}

class standard_format.StandardFormatComments #0BED99 {
	-_automatic_qc
	-_info
	-_path
	info_tags, @p
==
	+get_automatic_qc_datetimes()
	+has_automatic_qc_today()
	+save_comment_info()
	-_automatic_qc_date_from_comment_line(), @sm
	-_automatic_qc_datetime_from_comment_line(), @sm
	-_automatic_qc_matches_today()
	-_save_comment_line()
}

class vis_qc.VisQC #323231 {
	+bokeh_app_file_path
	+bokeh_child_process
	+data_directory
	+filters
	+settings_argument_file_path
	+visualize_setting
==
	+start()
	+stop()
	-_create_settings_argument_file()
}

class xmlcon_file.XMLCONfile #AE2690 {
	+file_path
	+tree
	serial_number, @p
==
	+get_sensor_info()
	+print_sensors()
}


cnv_column_info.CnvSensorInfo <|-- dict

exceptions.CTDException <|-- Exception

exceptions.MissingAttribute <|-- exceptions.CTDException

exceptions.UnrecognizedFileName <|-- exceptions.CTDException

exceptions.InvalidInstrumentName <|-- exceptions.CTDException

exceptions.InvalidInstrumentSerialNumber <|-- exceptions.CTDException

exceptions.InvalidDateFormat <|-- exceptions.CTDException

exceptions.InvalidTimeFormat <|-- exceptions.CTDException

exceptions.InvalidCountryCode <|-- exceptions.CTDException

exceptions.InvalidSerialNumber <|-- exceptions.CTDException

exceptions.InvalidFileNameFormat <|-- exceptions.CTDException

exceptions.PathError <|-- exceptions.CTDException

exceptions.InvalidSurfacesoak <|-- exceptions.CTDException

exceptions.InvalidParameterIndex <|-- exceptions.CTDException

exceptions.FileExists <|-- exceptions.CTDException

former_seabird.BlFile <|-- former_seabird.SeabirdRawFileBase

former_seabird.BtlFile <|-- former_seabird.SeabirdRawFileBase

former_seabird.HdrFile <|-- former_seabird.SeabirdRawFileBase

former_seabird.HexFile <|-- former_seabird.SeabirdRawFileBase

former_seabird.RosFile <|-- former_seabird.SeabirdRawFileBase

former_seabird.XmlconFile <|-- former_seabird.SeabirdRawFileBase

former_seabird.ConFile <|-- former_seabird.SeabirdRawFileBase

former_ship.FinnishShip <|-- former_ship.Ship

former_ship.SBE09 <|-- former_ship.Ship

former_ship.Dana <|-- former_ship.Ship

former_ship.Aranda <|-- former_ship.FinnishShip

former_ship.Aura <|-- former_ship.FinnishShip

former_ship.Meri <|-- former_ship.FinnishShip

former_ship.Svea <|-- former_ship.Ship

_old_ctd_sbe9_processing.CtdProcessing <|-- object

parent_abc_class.CTDFiles <|-- ABC

file_pattern_nodc.NODCSBECTDFiles <|-- modify.ModifyCTDfiles

file_pattern_old_processing_script.OldSBECTDFiles <|-- modify.ModifyCTDfiles

modify.ModifyCTDfiles <|-- sbe_parent_class.SBECTDFiles

sbe_parent_class.SBECTDFiles <|-- parent_abc_class.CTDFiles

derive.DerivePSAfile <|-- psa_file.PSAfile

loopedit.LoopeditPSAfile <|-- psa_file.PSAfile

psa_file_with_plot.PSAfileWithPlot <|-- psa_file.PSAfile

psa_plot_file.PlotPSAfile <|-- psa_file_with_plot.PSAfileWithPlot

seasave.SeasavePSAfile <|-- psa_file_with_plot.PSAfileWithPlot

cnv_column_info.CnvInfoFile o-- cnv_column_info.CnvSensorInfo

cnv_column_info.CnvInfoFiles o-- cnv_column_info.CnvInfoFile

file_handler.SBEFileHandler o-- file_handler.File
file_handler.SBEFileHandler o-- file_handler.File

former_cnv.CNVfile o-- former_cnv.CNVheader
former_cnv.CNVfile o-- former_cnv.CNVparameter
former_cnv.CNVfile o-- cnv_header.CNVheader
former_cnv.CNVfile o-- cnv_parameter.CNVparameter

former_processing.CtdProcessing o-- former_processing.Paths
former_processing.CtdProcessing o-- former_processing.SetupFile
former_processing.CtdProcessing o-- former_processing.BatchFile
former_processing.CtdProcessing o-- cnv_column_info.CnvInfoFiles
former_processing.CtdProcessing o-- former_cnv.CNVfile
former_processing.CtdProcessing o-- former_seabird.SeabirdFiles
former_processing.CtdProcessing o-- cnv_file.CNVfile

former_seabird.SeabirdFiles o-- former_seabird.BlFile
former_seabird.SeabirdFiles o-- bl_file.BlFile

metadata.MetadataFile o-- metadata.MetadataRow

standard_format.StandardFormatComments o-- standard_format.StandardFormatComments

_old_ctd_sbe9_processing.CtdProcessing o-- _old_ctd_sbe9_processing.CtdProcessing
_old_ctd_sbe9_processing.CtdProcessing o-- file_handler.File
_old_ctd_sbe9_processing.CtdProcessing o-- former_processing.CtdProcessing
_old_ctd_sbe9_processing.CtdProcessing o-- former_ship.Dana
_old_ctd_sbe9_processing.CtdProcessing o-- former_ship.Svea

cnv_file.CNVfile o-- cnv_column_info.CnvInfoFiles
cnv_file.CNVfile o-- former_cnv.CNVheader
cnv_file.CNVfile o-- former_cnv.CNVparameter
cnv_file.CNVfile o-- cnv_header.CNVheader
cnv_file.CNVfile o-- cnv_parameter.CNVparameter

standard_format.CreateStandardFormat o-- data_delivery.DeliveryMetadataFile
standard_format.CreateStandardFormat o-- delivery_note.DeliveryNote
standard_format.CreateStandardFormat o-- metadata.MetadataFile
standard_format.CreateStandardFormat o-- sensor_info_file.SensorInfoFiles

former_processing.SetupFile o-- file_handler.File

modify.ModifyCTDfiles o-- former_cnv.CNVfile
modify.ModifyCTDfiles o-- cnv_file.CNVfile

sbe_parent_class.SBECTDFiles o-- former_seabird.HdrFile
sbe_parent_class.SBECTDFiles o-- former_seabird.BlFile
sbe_parent_class.SBECTDFiles o-- cnv_file.CNVfileInfo
sbe_parent_class.SBECTDFiles o-- bl_file.BlFile
sbe_parent_class.SBECTDFiles o-- hdr_file.HdrFile

sbe_processing.SBEProcessing o-- sbe_batch_file.SBEBatchFile
sbe_processing.SBEProcessing o-- sbe_setup_file.SBESetupFile
sbe_processing.SBEProcessing o-- loopedit.LoopeditPSAfile

sbe_setup_file.SBESetupFile o-- psa_plot_file.PlotPSAfile

sensor_info_file.SensorInfoFile o-- param_reported.ParamReported
sensor_info_file.SensorInfoFile o-- cnv_file.CNVfileXML

sensor_info_file.SensorInfoFiles o-- sensor_info_item.SensorInfoItem

param_reported.ParamReported o-- cnv_file.CNVfileXML

@enduml